/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Stack;

import java.util.*;

public class App {

    public static void main(String[] args) {
        Stack stack = new Stack();
        System.out.println("Stack : "+ stack);
        
        showPush(stack, 42);
        showPush(stack, 55);
        showPush(stack, 20);
        showPush(stack, 65);

        showPop(stack);
        showPop(stack);
        showPop(stack);
        showPop(stack);

        try {
            showPop(stack);
        } catch (EmptyStackException e) {
            System.out.println("Stack Kosong");
        }
    }

    // memasukan element ke dalam stack
    static void showPush(Stack stack, int a){
        stack.push(new Integer(a));
        System.out.println("push("+a+")");
        System.out.println("stack: " + stack);
    }

    static void showPop(Stack stack){
        System.out.print("pop -> " );
        Integer a = (Integer)stack.pop();
        System.out.println(a);
        System.out.println("Stack:" + stack);
    }

}
