/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LamdaExpression;

public class App {

    public static void main(String[] args) {

        FuncInterface iFuncInterface = (int z, int p)->System.out.println(3*z*p);
        iFuncInterface.abstractFun(5, 6);

    }
}

interface FuncInterface{
    
    // fungsi abstrak dimana minimal harus ada satu parameter
    void abstractFun(int x, int y);

    // bukan fungsi abstrak
    default void normalFun(){
        System.out.println("hhaii");
    }
}