/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Properties;

import java.util.Iterator;
import java.util.Properties;
import java.util.Set;

public class App {


    public static void main(String[] args) {

        Properties capitals = new Properties();
        Set state = null;
        String str;

        capitals.put("Illinois", "SpringField");
        capitals.put("Missouri", "Jefferson City");
        capitals.put("Washington", "Olympia");
        capitals.put("California", "Sacramento");
        capitals.put("Indiana", "Indianapolis");

        System.out.println(String.valueOf(state));
        state = capitals.keySet(); // mengambil nilai key

        Iterator iterator = state.iterator();

        while (iterator.hasNext()) {
            str = (String)iterator.next();
            System.out.println("The capital of "+ str + " is "+ capitals.getProperty(str));
        }
        System.out.println();

        str = capitals.getProperty("Florida", "Not found");
        System.out.println("The capital of florida is : " + str + ".");

    }
}
