/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.oop.customer;

import java.util.*;

public class App {

    public static void main(String[] args) {

        Customer customer1 = new Customer("Eko", "Palembang");
        Order oder1 = new Order("baju", 25000, 2);
        customer1.order(oder1);

        Customer customer2 = new Customer("Andi", "Yogyakarta");
        Order oder2 = new Order("celana", 50000, 4);
        customer2.order(oder2);


    }
}
