/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HashTable;

import java.util.*;

public class App {

    public static void main(String[] args) {

        // membuat hash map
        Hashtable balanceHashtable = new Hashtable();
        Enumeration names;
        String str;
        double bal;

        balanceHashtable.put("Zara", new Double(3434.34));
        balanceHashtable.put("Mahnaz", new Double(123.34));
        balanceHashtable.put("Ayan", new Double(321.123));
        balanceHashtable.put("Daisy", new Double(342.54));
        balanceHashtable.put("Qadir", new Double(-19.08));

        names = balanceHashtable.keys();

        while (names.hasMoreElements()) {
            str = (String)names.nextElement();
            System.out.println(str + ": " + balanceHashtable.get(str));
        }

        /**
         * nilai yang sudah di tambahkan atau put, ingin di tambahkan lagi,
         * apabila antara key dan value yang lama dengan baru sama, maka data tidak akan berubah
         * namun apabila salah satu saja beda maka akan di tambahkan hashTable baru lagi
         */

        // memasukan nilai 1.000 ke akun zara
        bal = ((Double)balanceHashtable.get("Zara")).doubleValue();
        balanceHashtable.put("Zara", new Double(bal + 1000));
        System.out.println("saldo Zara yang baru pertama: " + balanceHashtable.get("Zara"));
        balanceHashtable.put("Zara", new Double(bal + 2000));
        System.out.println("saldo Zara yang baru kedua: " + balanceHashtable.get("Zara"));
        balanceHashtable.put("zara", new Double(2000));
        System.out.println("saldo zara z kecil : " + balanceHashtable.get("zara"));

    }
}
