/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Enumeration;

import java.util.*;

public class App {

    @SuppressWarnings("unchecked")
    public static void main(String[] args) {
        Enumeration days;
        Vector daysName = new Vector();

        daysName.add("Sunday");
        daysName.add("Monday");
        daysName.add("Tuesday");
        daysName.add("Wednesday");
        daysName.add("Thursday");
        daysName.add("Friday");
        daysName.add("Saturday");

        days = daysName.elements();

        while (days.hasMoreElements()) {
            System.out.println(days.nextElement());
        }

        // System.out.println(daysName);
    }
}
