/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Vector;

import java.util.*;

public class App {

    public static void main(String[] args) {

        // ukuran awal nilai nya 3, nilai kenaikan/increment 2
        Vector vector = new Vector(3,2);
        System.out.println("Initial size: " + vector.size());
        System.out.println("Initial capacity: " + vector.capacity());
        
        vector.addElement(new Integer(1));
        vector.addElement(new Integer(2));
        vector.addElement(new Integer(3));
        vector.addElement(new Integer(4));

        /**  
         * capacity ditambahkan sebanyak nilai kenaikan/increment di awal
         * jika element yang ditambahkan lebih dari nilai awal
         * atau capacity otomatis di tambahkan ketika ukuran element lebih dari nilai awal
        */
        System.out.println("Capacity after additions: "+ vector.capacity()); 
        System.out.println("Size after additions: "+ vector.size());

        vector.addElement(new Double(5.45));
        vector.addElement(new Integer(7));
        System.out.println("Current capacity: "+ vector.capacity());

        System.out.println("First element: "+ (Integer)vector.firstElement());
        System.out.println("Last element: "+ (Integer)vector.lastElement());
        
        if (vector.contains(new Integer(3))) {
            System.out.println("Vector contains 3");
        }

        // enumerasi element dalam vector
        Enumeration enumeration = vector.elements();
        System.out.println("\nElement in vector");

        while (enumeration.hasMoreElements()) {
            System.out.println(enumeration.nextElement() + " ");
            System.out.println();
        }
    }
}
