/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.json.simple;

public class App {

    public static void main(String[] args) {

      JSONObject json = new JSONObject();
      
      json.put("name", "apple");

      System.out.println(json);
    }
}
