/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kasus;

import org.junit.Test;
import static org.junit.Assert.*;


public class AppTest {


    @Test
    public void testAreaRectOne(){
        Point originOne = new Point(23, 94);
        Rectangle rectOne = new Rectangle(originOne, 100, 200);

        assertEquals(20000, rectOne.getArea());
    }
}
