/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package XML;

import java.io.File;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

public class App {


    public static void main(String[] args) {
        try {
            File inputFile = new File("input.txt");
            DocumentBuilderFactory dBuilderFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder documentBuilder = dBuilderFactory.newDocumentBuilder();
            Document document = documentBuilder.parse(inputFile);
            document.getDocumentElement().normalize();
            System.out.println("Root element :"+ document.getDocumentElement().getNodeName());
            
            NodeList nodeList = document.getElementsByTagName("student");

            System.out.println("----------------------------");
            for (int i = 0; i < nodeList.getLength(); i++) {
                Node node = nodeList.item(i);
                System.out.println("\nCurrent Element :"+ node.getNodeName());
                if (node.getNodeType() == Node.ELEMENT_NODE) {
                    Element element = (Element) node;
                    System.out.println("Studen roll no : " + element.getAttribute("rollno"));
                    System.out.println("First name : " + element.getElementsByTagName("firstname").item(0).getTextContent());
                    System.out.println("Last name : " + element.getElementsByTagName("lastname").item(0).getTextContent());
                    System.out.println("Nick Name : " + element.getElementsByTagName("nickname").item(0).getTextContent());
                    System.out.println("Marks : " + element.getElementsByTagName("marks").item(0).getTextContent());
                }
            }

        } catch (Exception e) {
            //TODO: handle exception
        }
    }
}
