/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bitset;

import java.util.BitSet;

public class App {


    public static void main(String[] args) {
        BitSet bits1 = new BitSet(16);
        BitSet bits2 = new BitSet(16);

        // mengisi bits
        for (int i = 0; i < 16; i++) {
            if((i % 2) == 0) bits1.set(i);
            if((i % 5) != 0) bits2.set(i);
        }

        System.out.println("inisial awal pada bits1");
        System.out.println(bits1);
        System.out.println("\ninisial awal pada bits2");
        System.out.println(bits2);

        // Operasi AND
        bits2.and(bits1);
        System.out.println("\nBits2 And bits2 : ");
        System.out.println(bits2);

        // Operasi OR
        bits2.or(bits1);
        System.out.println("\nBits2 Or bits1");

        // Operasi XOR
        bits2.xor(bits1);
        System.out.println("\nBits2 XOR bits1");
        System.out.println(bits2);
        

    }
}
