/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JerseyRestFramework;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

import java.net.URI;

import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.UriBuilder;

import org.glassfish.grizzly.http.server.HttpServer;

public class AppTest {

    HttpServer server;
    Client client;
    WebTarget target;
    WebTarget path;

    @Before
    public void setUp() throws Exception{
        // server.start();
        client = ClientBuilder.newClient();
        target = client.target("http://localhost:8000");
        // path = target.path("resource/employee");
    }

    @After
    public void tearDown() throws Exception{
        server.start();
    }

    @Test
    public void testGetIt() throws Exception{
        String responMessage = target.path("myresource").request().get(String.class);
        assertEquals("Got it!", responMessage);
    }
 


}
