/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Serialization;


import java.io.*;

public class App{
    
    public static void main(String[] args) {
        
        Demo object = new Demo(1, "Eko Muliyo");
        String filename = "file.ser";

        // Serialization
        try {
            
            // menyimpan object dalam file
            FileOutputStream file = new FileOutputStream(filename);
            ObjectOutputStream out = new ObjectOutputStream(file);

            // method untuk membuat serialization dari object
            out.writeObject(object);
            out.close();
            file.close();

            System.out.println("Object telah di serialisasi");
        } catch (IOException e) {
            System.out.println("IOException is caught");
        }

        Demo object1 = null;

        // Deserialization
        try {
            FileInputStream file = new FileInputStream(filename); // filename letaknya harus di diluar diluar folder atau sejajar dengan struktur project
            ObjectInputStream filein = new ObjectInputStream(file);

            // Method for deserialiazation dari object
            object1 = (Demo)filein.readObject();
            filein.close();
            file.close();

            System.out.println("Object telah di serialization");
            System.out.println("a = "+ object.a);
            System.out.println("b = "+ object.b);
        } catch (IOException e) {
            System.out.println("IOException telah di dapatkan");
        } 
        catch(ClassNotFoundException ex) { 
            System.out.println("ClassNotFoundException is caught"); 
        } 
        
    }
}

class Demo implements Serializable{
    public int a;
    public String b;

    public Demo(int a, String b){
        this.a = a;
        this.b = b;
    }
}

